edocs.token-url=${EDOCS_TOKEN_URL:${api.e-docs.uri.token:https://acessocidadao.es.gov.br/is/connect/token}}
edocs.api-url=${EDOCS_API_URL:${api.e-docs.uri.webapi:https://api.e-docs.es.gov.br}}
edocs.client-id=${EDOCS_CLIENT_ID:${api.e-docs.client-id:${api.acessocidadao.client-id:}}}
edocs.client-secret=${EDOCS_CLIENT_SECRET:${api.e-docs.client-secret:${api.acessocidadao.client-secret:}}}
edocs.grant-type=${EDOCS_GRANT_TYPE:${api.e-docs.grant_type:client_credentials}}
edocs.scope=${EDOCS_SCOPE:${api.e-docs.scope:api-sigades-consultar ApiOrganograma}}
edocs.priority-external-identifier=${EDOCS_PRIORITY_EXTERNAL_IDENTIFIER:${api.e-docs.identificador-externo.processo-prioritario:}}
edocs.max-in-memory-size=${EDOCS_MAX_IN_MEMORY_SIZE:16777216}
